### ISSUE TITLE
SD card status not auto-updating

### ISSUE THREAD

**Issue by Kibouo** [rayshift/translatefgo#1]
This is a QoL bug.

When opening the app the 1st time, it asks storage permissions. But because these are not yet granted, the app displays that it cannot find the SD card.

Giving permissions works. However, it keeps saying no SD card detected until you restart.

**Comment by neobenedict** [comment]
Hello, what android version? The app should ask you for permissions when it starts.

**Comment by Kibouo** [comment]
This is not an Android bug. It's a QoL bug.
> [...] it asks storage permissions
> Giving permissions works
It just doesn't auto-refresh the SD card status *after* having given the permission.

**Comment by Kibouo** [comment]
You can drag down to refresh. That works too.
