### ISSUE TITLE
Android 11?

### ISSUE THREAD

**Issue by FrejaSE** [rayshift/translatefgo#17]
Why no Android 11 support? I'm just curious as some Devices auto update.

**Comment by neobenedict** [comment]
New android security makes it impossible, the FGO asset folder is no longer readable. You will have to downgrade your device or move your SD card to an android 10 device every time you want to update the scripts. There is no workaround.

**Comment by FrejaSE** [comment]
I see. That's very unfortunate.

**Comment by neobenedict** [comment]
The other alternatives are a rooted device or modified APK, but I don't support either right now. There may be support in the future.

**Comment by Wescj** [comment]
Is there still no support for android 11?

**Comment by neobenedict** [comment]
No. It's not a simple fix. Blame google.
