### ISSUE TITLE
Future Android 11 support

### ISSUE THREAD

**Issue by FrejaSE** [rayshift/translatefgo#18]
Will your team ever support android 11 in the future. If any backdoors, etc are discovered?
There's also this I found if it can be to any help.
[](https://developer.android.com/about/versions/11/privacy/storage) 
![SmartSelect_20201221-132007_Chrome](https://user-images.githubusercontent.com/52380137/102776695-807d1f00-438f-11eb-94b3-29b90763b23d.jpg)
![SmartSelect_20201221-131947_Chrome](https://user-images.githubusercontent.com/52380137/102776731-92f75880-438f-11eb-9d7b-c96cc387c997.jpg)

**Comment by neobenedict** [comment]
https://github.com/rayshift/translatefgo/issues/17

I don't think requestLegacyExternalStorage worked last time I tried it. I can try again.

**Comment by FrejaSE** [comment]
Thanks that would be most appreciated, cause if it does indeed work has intended it'll help future proofing the application.

**Comment by FrejaSE** [comment]
Any progress Neo?

**Comment by neobenedict** [comment]
Is a windows app that you plug your phone into your PC to update the scripts acceptable? It's the only way...

**Comment by FrejaSE** [comment]
I mean.. it's something. It works

**Comment by FrejaSE** [comment]
I'm not the voice of everyone, but I can say that it's better than not having any translations at all.

**Comment by FrejaSE** [comment]
> Is a windows/mac/linux app that you plug your phone into your PC to update the scripts acceptable? It's the only way...

Yes it is. It would still be as easy right?

**Comment by neobenedict** [comment]
> 
> 
> > Is a windows/mac/linux app that you plug your phone into your PC to update the scripts acceptable? It's the only way...
> 
> Yes it is. It would still be as easy right?

In theory. Don't expect it any time soon though, very busy right now. I'll have it ready maybe February.

**Comment by FrejaSE** [comment]
> > > Is a windows/mac/linux app that you plug your phone into your PC to update the scripts acceptable? It's the only way...
> > 
> > 
> > Yes it is. It would still be as easy right?
> 
> In theory. Don't expect it any time soon though, very busy right now. I'll have it ready maybe February.

Sounds reasonable. Love the work your team are doing

**Comment by neobenedict** [comment]
Good news, using https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE and targetting an old version of android seems to work. I hope. So I'll get this implemented soon.

**Comment by neobenedict** [comment]
2.0.0 fixes this issue.
