### ISSUE TITLE
Provide clarity on what the application is actually doing for the general public

### ISSUE THREAD

**Issue by enshael** [rayshift/translatefgo#2]
The translatefgo app modifies the FGO application's resources. Even if it's not modifying the APK directly, it can still be considered as a modification of the application in some cases.

Can you put in additional details on how the application works (reading the FGO resource folder and replacing the files with the translated versions), so people using this app will be aware of the risks that they're getting into when using this app?

**Comment by neobenedict** [comment]
It does not modify executable code (which is the term "Application"). The Terms of Service has separate clauses for "Game data" including text, and does not forbid modification.

Even if it did, the game has no detection, it can't even detect hacked APKs, so there's nothing to worry about. The game used to be able to detect certain things such as root, emulators, modified apks, and sent it as part of the user login process, but this was removed with the engine update last June.

I would not release this application to the public if I was not 100% convinced it was safe.

**Comment by enshael** [comment]
Thanks! I was mostly concerned on people installing the app without being aware of what it specifically does. 

We'll never know when DW will change stances on stuff like these, all they need is to put in a hash check on the resource files and everyone with modified resources may get screwed.

**Comment by neobenedict** [comment]
A hash check would also be tripped up by corrupted files, so it's not reliable. Either way if an update is introduced (I check every update) specifically to target this app, I will take the appropriate action.
