### ISSUE TITLE
No SD card slot

### ISSUE THREAD

**Issue by JeyMoh** [rayshift/translatefgo#22]
![Screenshot_20210312-233907](https://user-images.githubusercontent.com/80535226/110962726-3bfc9080-838c-11eb-9ded-2d6124542fe4.jpg)

**Comment by JeyMoh** [comment]
help my phone does not have a SD card slot

**Comment by neobenedict** [comment]
Hi,

We're working on an updated version of the app that fixes this issue. It should be ready next week, please check back then.

Kind regards

**Comment by JeyMoh** [comment]
Ohh Ic.Thanks for ur guys' effort to help the community.

**Comment by neobenedict** [comment]
2.0.0 fixes this issue.
