### ISSUE TITLE
About a Portuguese Brazilian translation.

### ISSUE THREAD

**Issue by rohanoso** [rayshift/translatefgo#25]
So, I'm from a brazilian Facebook/Twitter page called "Fate Works", and our team is actually interested in manually translating the game's main quest by it's entirely, from Fuyuki to LB3 and further beyond (And maybe, in the future, events and interludes too). 

We got invested into doing this after knowing about the recent update in the app, including NA supports. Since many people for our country actually can't read English, we are willing to help them with a translation for the game.

So, are us allowed to do it? If yes, how could we start?

**Comment by neobenedict** [comment]
Can you link your facebook/twitter page?

And does your language have any non-latin characters?

**Comment by rohanoso** [comment]
https://twitter.com/fate_works

**Comment by rohanoso** [comment]
https://twitter.com/fate_works
https://www.facebook.com/search/top?q=Fate%20Works
There are the links..

Also, our team have 6 members actually, and finally, brazilian portuguese is pretty fine with the characters. I've tested pretty much all we have using the Master's name and the message in-game, and they seem to work well. The test was on the NA server, if it works there, it must works on JP too.

**Comment by neobenedict** [comment]
OK. We have a spanish translation already, would read-only access to that be of any use? I don't know how similar the languages are.

Otherwise join the discord, nominate a leader who will coordinate everything and I can get you started.

**Comment by rohanoso** [comment]
The languages have some similarities, but we should be better translating from English anyway. Just our preference.
And we will be joining the discord soon
