### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Musashisama12** [rayshift/translatefgo#27]
![Screenshot_2021-03-25-09-39-36-16](https://user-images.githubusercontent.com/81338950/112405951-3a4ca880-8d4e-11eb-9dea-aae2c71f013d.png)

**Comment by neobenedict** [comment]
Can you try the android 11 setup in the about tab?

**Comment by Musashisama12** [comment]
I tried it, set the directory to android, and now I just get a loading screen

**Comment by neobenedict** [comment]
Restart the app, and loading might take a while if on an emulator or slow phone

**Comment by Musashisama12** [comment]
yeah it works now, thank you.
