### ISSUE TITLE
Brazilian Support

### ISSUE THREAD

**Issue by AkkuaMagunusu** [rayshift/translatefgo#28]
Hello, I recently met your work and found it incredible, thank you, it really helps a lot!
What I would like to know is whether you would be willing to implement a Brazilian Portuguese translation in the Program, if that would be possible ... The PT-BR FGO Community is VERY large, but unfortunately there is no apparent interest in bringing the game here :/
There are already several direct translations of all the lines of the Game in Portuguese for some Fandom Pages (Fuyuki - LB5), all in Documents on Google Drive, would it be a quicker step to help? I don't know how your work works, if it is possible to get something already written or if it is an automatic translation of Zero and then revising... Anyway, thanks!

**Comment by neobenedict** [comment]
Hi,

It's being worked on at the moment, there should be a further announcement next month.
