### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by safire9** [rayshift/translatefgo#29]
how to fixed :

Internal Error An internal error has occurred, please report this as a bug.  

System.NullReferenceException: Object reference not set to an instance of an object at RayshiftTranslateFGO.Droid.  Content / Manager.GetlnstalledGameApps (RayshiftTranslateFGO.Services. ContentType accessType, System.String storagelocation) [Ox0003f] in <28feaeOf58d94348828d24c99087875 3> 0 at RayshiftTranslateFGO.Views.  InstallerPage.UpdateTranslationList () (0x001661 in <d4494e690e l4468ebd622b9622833e d7> 0

??

**Comment by neobenedict** [comment]
Need your android version and phone model

**Comment by safire9** [comment]
> Need your android version and phone model

Android 5, Oppo F1s

**Comment by neobenedict** [comment]
Reinstall the app

Otherwise go to the "about" tab and click "Android 11 setup"

**Comment by safire9** [comment]
> Reinstall the app
> 
> Otherwise go to the "about" tab and click "Android 11 setup"

Ah, Thank you for the help🙏💖
