### ISSUE TITLE
Error while updating translation package

### ISSUE THREAD

**Issue by lightspect** [rayshift/translatefgo#3]
I ran into a problem while updating the Official & Machine TL package today. The update start off fast, up to 3/9 package, then it slow to almost a halt, after a while it show error like
![Screenshot_20200527-230750](https://user-images.githubusercontent.com/66027624/83048032-48b92d80-a073-11ea-86bc-ae807ba9acee.jpg)
Also I see that some event from 2017 until now has not been translated, should I install another one or because those translation has not been updated? I would love to contribute to it.

**Comment by neobenedict** [comment]
I fixed cloudflare's caching, try again and see if it's any better.

Event from 2017 onwards as well as LB2-LB5 is not translated yet, maybe soon.

**Comment by lightspect** [comment]
That's strange? Since the NA one is already on 2018 content of the JP server so I think at least those from 2017 to the start of 2018 should have official translation. Or it is not available yet to the public?

**Comment by neobenedict** [comment]
Oh, you are right, 2018 onwards. What 2017 events are not translated properly?

**Comment by lightspect** [comment]
Oh sorry I was mistaken one of the Ryo style event of 2019 for the Paul Bunyan event. Just recheck some and all of the checked one are translated
