### ISSUE TITLE
Bugs on Android 10

### ISSUE THREAD

**Issue by wyyr** [rayshift/translatefgo#32]
[https://ibb.co/hfLSJFT](https://ibb.co/hfLSJFT) 

Hi, i want to report because the app doesn't run at all on my phone.

Device: Realme RMX1821
OS: Android 10
App version: 2.0.5

**Comment by neobenedict** [comment]
Go to the about tab and click "Reconfigure for Android 11 (or similar, forget the exact wording)".

**Comment by neobenedict** [comment]
Fixed 2.0.7
