### ISSUE TITLE
Add Russian translate

### ISSUE THREAD

**Issue by AbobaVa** [rayshift/translatefgo#35]
Will there be added options in the application to play with the Russian translation?

**Comment by neobenedict** [comment]
Russian font isn't supported and work to modify the font stalled last year. If I have time I will revisit it.

**Comment by Ivan-Q95** [comment]
I endorse this topic. It would be nice to have a Russian translation

**Comment by neobenedict** [comment]
Closing this as it isn't on the roadmap for this project - lack of ability to change font & certain geopolitical events make this not worth persuing further for the immediate future.
