### ISSUE TITLE
Error while i tried to download the files

### ISSUE THREAD

**Issue by Mukushiki09** [rayshift/translatefgo#4]
![Screenshot_20200528-092914](https://user-images.githubusercontent.com/66045945/83089130-1dacf900-a0c8-11ea-9242-b51f42274df8.png)

I tried to download the TL event files from yesterday but it says error when i touch the 3 of 6 files and 5 of 6 files mark. How to fix this?

**Comment by neobenedict** [comment]
Hi,

Is this still an issue? I enabled cloudflare caching for these files so try again.

**Comment by Mukushiki09** [comment]
It still says error. Well maybe it doesn't support my phone, idk :(
