### ISSUE TITLE
Question about the multiple install options

### ISSUE THREAD

**Issue by contown** [rayshift/translatefgo#42]
When I open the app there's an option to install an english full TL that includes LB6, and an option to just install LB6. Do they overlap? Can/should I install both? I installed the LB6 one and it's working well, but in hindsight I think I should've installed the full one? I don't know if overlapping will mess my game or anything.

**Comment by neobenedict** [comment]
You can install both or either, it won't break anything. The LB6 option was added separately so people aren't confused about where to get it.
