### ISSUE TITLE
Can't Select Android Folder on Pixel 6 Android 12

### ISSUE THREAD

**Issue by frosteeze** [rayshift/translatefgo#43]
I was not able to select the android folder required on the app. It says "To protect your privacy, choose another folder." I've also tried to downgrade the Android Files app to a lower version since that used to be one way to get around the problem. 

I was able to access the folder using a different app. Is it possible maybe to just manually copy paste files? I'm not really sure how to resolve this automatically. 

I am on Android 12

**Comment by neobenedict** [comment]
Downgrade to Android 11, this app isn't compatible with Android 12.

**Comment by frosteeze** [comment]
I think there was a recent update to Android or maybe I just restarted my device, but I was able to get this working again. Not sure how.

Regardless, I do think future Android updates will break this app because of Google's intention so I would leave the readme as is. Android 11 should still be recommended. We can keep the issue as closed. 

Just for future people: 
1. Check if your version of android is android 12 beta 3.1. 
2. If higher, attempt to revert the files app version using the .apk that's floating around. 
3. If that doesn't work, make sure you have latest updates since the only way is up, restart, and check if you can read/write to the android folder using another file explorer app like SolidExplorer.

**Comment by neobenedict** [comment]
> I think there was a recent update to Android or maybe I just restarted my device, but I was able to get this working again. Not sure how.
> 
> Regardless, I do think future Android updates will break this app because of Google's intention so I would leave the readme as is. Android 11 should still be recommended. We can keep the issue as closed.
> 
> Just for future people:
> 
>     1. Check if your version of android is android 12 beta 3.1.
> 
>     2. If higher, attempt to revert the files app version using the .apk that's floating around.
> 
>     3. If that doesn't work, make sure you have latest updates since the only way is up, restart, and check if you can read/write to the android folder using another file explorer app like SolidExplorer.

Do you have a link to that .apk?

But yeah, this is entirely google's fault (voice your concern here: https://issuetracker.google.com/issues/196422354)

**Comment by frosteeze** [comment]
> > I think there was a recent update to Android or maybe I just restarted my device, but I was able to get this working again. Not sure how.
> > Regardless, I do think future Android updates will break this app because of Google's intention so I would leave the readme as is. Android 11 should still be recommended. We can keep the issue as closed.
> > Just for future people:
> > ```
> > 1. Check if your version of android is android 12 beta 3.1.
> > 
> > 2. If higher, attempt to revert the files app version using the .apk that's floating around.
> > 
> > 3. If that doesn't work, make sure you have latest updates since the only way is up, restart, and check if you can read/write to the android folder using another file explorer app like SolidExplorer.
> > ```
> 
> Do you have a link to that .apk?
> 
> But yeah, this is entirely google's fault (voice your concern here: https://issuetracker.google.com/issues/196422354)

This is the .apk I tried: https://drive.google.com/file/d/1-8spf-LQ-VDHOl3zThzWWkd7POgM5KA9/view

When I tried to update the files app this way using the default package installer it says it was not valid, but somehow I opened up the translator app this morning and it works so, I don't know. Computers huh?

And yeah, I do recommend everyone reading to star and comment that issue so we can get traction. Good call.
