### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Kortohq** [rayshift/translatefgo#44]
App doesn't work,i tried installing old versions that worked before, but they don't work too.

![Screenshot_2021-12-23-11-23-01-149_io rayshift translatefgo](https://user-images.githubusercontent.com/96569379/147212914-0d51a786-a7ed-481f-8fed-8e38b18cd82c.jpg)

**Comment by neobenedict** [comment]
It should be fixed, there was a temporary issue.
