### ISSUE TITLE
Indonesian support

### ISSUE THREAD

**Issue by niizam** [rayshift/translatefgo#45]
First of all I want to thank you for making this great project.
I found some difficulty understanding English because it's not my native language and I can't digest its meaning comprehensively, neither do most people in my country.
Indonesian language also has 100% compatibility characters with English.
Hereby, would it be possible to add Indonesian translation and would you implement it?
There is also a [blog site](https://sehai-kun.blogspot.com/2020/09/sixth-singularity-camelot-chapter-17_22.html) which has translated stories up to Camelot that might help.

Sincerely yours.

**Comment by neobenedict** [comment]
Other languages are a possiblity in the future, if you can gather a large enough team.

**Comment by Sircuit** [comment]
@neobenedict what is the mechanism so that we can help add Indonesian translations to this project? I'm happy to help translate all the stories in FGO But applying it to this project is the problem

**Comment by ADFS1234** [comment]
can i join to help this project?

**Comment by VhalennnG** [comment]
Can i join this project? I'm happy to help make this project successful

**Comment by VhalennnG** [comment]
hello, do you have any 


> First of all I want to thank you for making this great project. I found some difficulty understanding English because it's not my native language and I can't digest its meaning comprehensively, neither do most people in my country. Indonesian language also has 100% compatibility characters with English. Hereby, would it be possible to add Indonesian translation and would you implement it? There is also a [blog site](https://sehai-kun.blogspot.com/2020/09/sixth-singularity-camelot-chapter-17_22.html) which has translated stories up to Camelot that might help.
> 
> Sincerely yours.



> First of all I want to thank you for making this great project. I found some difficulty understanding English because it's not my native language and I can't digest its meaning comprehensively, neither do most people in my country. Indonesian language also has 100% compatibility characters with English. Hereby, would it be possible to add Indonesian translation and would you implement it? There is also a [blog site](https://sehai-kun.blogspot.com/2020/09/sixth-singularity-camelot-chapter-17_22.html) which has translated stories up to Camelot that might help.
> 
> Sincerely yours.

Hi, do you still commit to make fgo translation?

**Comment by VhalennnG** [comment]
@niizam Hello, how can i contact you??

**Comment by niizam** [comment]
@Sircuit @VhalennnG let's gather on discord
nizam#4190

**Comment by Sircuit** [comment]
@VhalennnG What's your discord name?

**Comment by neobenedict** [comment]
Completed.
