### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by noelahai** [rayshift/translatefgo#46]
![Screenshot_2022-01-22-04-40-55-76_92cea9120d7935c52750b287ede47956](https://user-images.githubusercontent.com/98190635/150607280-9b67f99d-5f67-4c16-8b44-c0195817e6b4.jpg)
I already downloaded the latest version, chose the language, agree to storage permission but I still got this message

**Comment by neobenedict** [comment]
What phone and android version?

**Comment by noelahai** [comment]
@neobenedict Oppo A53 Android 10

**Comment by noelahai** [comment]
It's fixed and now I can enjoy the story, thank you
