### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by infinityloop3** [rayshift/translatefgo#47]
![Screenshot_2022-01-31-06-19-14](https://user-images.githubusercontent.com/73043900/151722290-7f300d10-5155-4fd0-9727-868e0163e9a9.png)

So im using android 5.0, i already downloaded the latest version, chose the language, agree to storage permission button,  but I still got this message. (i also tried to choose the folder manually using "Reconfigure android 11 setup button", but it still doesn't work either)

**Comment by neobenedict** [comment]
Restart your phone and try again. Reinstall and try again if that doesn't work.

**Comment by infinityloop3** [comment]
> Restart your phone and try again. Reinstall and try again if that doesn't work.

Well... I've been trying it so many times, but still doesn't work for me. Do i need to root my phone?

**Comment by neobenedict** [comment]
No. What device is it?

**Comment by infinityloop3** [comment]
> No. What device is it?

Coolpad R108

**Comment by neobenedict** [comment]
"(i also tried to choose the folder manually using "Reconfigure android 11 setup button", but it still doesn't work either)"

And what "doesn't work"? Same error message?

**Comment by infinityloop3** [comment]
> "(i also tried to choose the folder manually using "Reconfigure android 11 setup button", but it still doesn't work either)"
> 
> And what "doesn't work"? Same error message?

![Screenshot_2022-01-31-10-21-53](https://user-images.githubusercontent.com/73043900/151734649-f0c92718-8fd8-4b71-952d-a4696eb49a75.png)

This kind of message. I have installed the game, and also downloaded the data

**Comment by neobenedict** [comment]
> > "(i also tried to choose the folder manually using "Reconfigure android 11 setup button", but it still doesn't work either)"
> > And what "doesn't work"? Same error message?
> 
> ![Screenshot_2022-01-31-10-21-53](https://user-images.githubusercontent.com/73043900/151734649-f0c92718-8fd8-4b71-952d-a4696eb49a75.png)
> 
> This kind of message. I have installed the game, and also downloaded the data

Okay, in the file manager, change from SD card to your internal storage, or vice versa, and try again.

What version of android?

**Comment by infinityloop3** [comment]
> > > "(i also tried to choose the folder manually using "Reconfigure android 11 setup button", but it still doesn't work either)"
> > > And what "doesn't work"? Same error message?
> > 
> > 
> > ![Screenshot_2022-01-31-10-21-53](https://user-images.githubusercontent.com/73043900/151734649-f0c92718-8fd8-4b71-952d-a4696eb49a75.png)
> > This kind of message. I have installed the game, and also downloaded the data
> 
> Okay, in the file manager, change from SD card to your internal storage, or vice versa, and try again.
> 
> What version of android?

I don't use SD card, so there's only internal storage in my phone, and that kind of message is the result. 

Android 5.1.1

**Comment by neobenedict** [comment]
Okay, if you open this Android/ folder in a normal file picker, do you see a "data" folder inside? Can you access it?

**Comment by infinityloop3** [comment]
> Okay, if you open this Android/ folder in a normal file picker, do you see a "data" folder inside? Can you access it?

![Screenshot_2022-01-31-12-31-09](https://user-images.githubusercontent.com/73043900/151743853-e54eb6b7-07f4-4e19-9737-97a7d1e9feea.png)
![1643607140914](https://user-images.githubusercontent.com/73043900/151743862-ccf69e5a-f65b-4f90-a475-0a4b32960ed8.jpg)

Yes i can, it looks like that

**Comment by neobenedict** [comment]
Closing, reopen if you still have trouble.
