### ISSUE TITLE
Servants abruptly disappearing in certain scenes

### ISSUE THREAD

**Issue by Nubum** [rayshift/translatefgo#50]
In some scenes, like the fog in chapter 19 of LB6 and parts of Baobhan Sith's valentine scene, Servants will abruptly vanish when they start talking. Servants do not disappear in the same scenes when the app isn't installed.

In Baobhan Sith's Valentine, it occurs in two places.
![image](https://user-images.githubusercontent.com/99936680/154609283-844ec76e-99bb-41ee-8b02-18c79a036d8a.png)
Baobhan Sith does not reappear again until she says "...Well, whatever, if that's the way it goes."
She disappears yet again when she says "I might as well make some chocolate too. Everyone needs a treat from time to time." and reappears at the next line when the scene changes. There are no more issues during the rest of the valentines scene.

During chapter 19-5 of LB6, the same issue persists for every Servant while the fog is on screen.

**Comment by neobenedict** [comment]
This should be fixed now, if it's still an issue please re-open.
