### ISSUE TITLE
Will Android 12 be supported eventually?

### ISSUE THREAD

**Issue by DeadlyPinkPanda** [rayshift/translatefgo#51]
I was wondering if you have any intention of adding support for Android 12. If so, any estimated time of delivery?

Thank you.

**Comment by dk-galeona** [comment]
i have a spare samsung s10 phone recently upgraded from android 11 to android 12 ，i dunno why but somehow this app is still working in android 12.  However i dare not to upgrade my main s20 phone with my main fgo account 🙈

**Comment by peaknot** [comment]
I'm on Android 12 and it works fine for me.

**Comment by dembercorrales01** [comment]
not working on android 12L

**Comment by stdedos** [comment]
[DocumentsUIGoogle.apk.zip](https://github.com/rayshift/translatefgo/files/8703105/DocumentsUIGoogle.apk.zip)

I also have this version - but it doesn't work for me either. Hopefully it saves someone else ❤️
_A renaming is required to use the file_

**Comment by neobenedict** [comment]
Android 12 should be properly supported with the next version.

**Comment by neobenedict** [comment]
Latest version now supports Android 12.
