### ISSUE TITLE
Menu translation

### ISSUE THREAD

**Issue by Lemonov-S** [rayshift/translatefgo#6]
Can the menus translation from NA version be ported? I'm new to F/GO so even though the story is translated, the menus are still confusing to navigate

**Comment by Arc-FGO** [comment]
Hi, menus are a different problem altogether, because of the following reasons:
1. They are images, not text
2. JP has a different layout than NA, which changes almost every month due to QoLs anyway.

**Comment by Lemonov-S** [comment]
What is the next best thing available then? Is there some sort of guide about quests and navigation somewhere? Can at least some parts of the menus be translated?

**Comment by neobenedict** [comment]
The menus can't be translated without modifying the APK, which adds a level of difficulty and breaks things like quartz payments so it's not really something we're looking to do at this time.
