### ISSUE TITLE
Linux compile

### ISSUE THREAD

**Issue by lucas-04** [rayshift/translatefgo#60]
I can compile this project with mono project + xamarin.android OSS installer or i need compile xamarin android?

**Comment by neobenedict** [comment]
I build on linux with the following:
```
msbuild /t:clean RayshiftTranslateFGO/RayshiftTranslateFGO.Android/RayshiftTranslateFGO.Android.csproj
msbuild /t:restore RayshiftTranslateFGO/RayshiftTranslateFGO.Android/RayshiftTranslateFGO.Android.csproj
msbuild /p:Configuration=Release /t:PackageForAndroid RayshiftTranslateFGO/RayshiftTranslateFGO.Android/RayshiftTranslateFGO.Android.csproj /p:AndroidSdkDirectory=/home/rayshift/android-toolchain/sdk /p:AndroidNdkDirectory=/home/rayshift/android-toolchain/ndk
```

MSBuild
```
msbuild -v
Microsoft (R) Build Engine version 16.6.0 for Mono
```

NDK
```
Pkg.Desc = Android NDK
Pkg.Revision = 21.1.6352462
```

SDK
```
AndroidVersion.ApiLevel=24
```


I recommend you download a pre-built release: https://github.com/rayshift/translatefgo/releases/download/2.0.8/io.rayshift.translatefgo-208.apk

**Comment by lucas-04** [comment]
I'm learning programming, would really like to compile the project as part of this.
But, I didn't even understand how to install the dependencies for this.

**Comment by neobenedict** [comment]
This is probably not the place to start as compiling Xamarin is an absolute nightmare. You would need the .net SDK (msbuild), and the android NDK and SDK.

**Comment by lucas-04** [comment]
![image](https://user-images.githubusercontent.com/95548091/189498571-c7a49272-4851-423e-8ade-f6a58a130a1c.png)

That really scared me, so I would like to know if I can use the precompiled version (xamarin.android-oss) https://dev.azure.com/xamarin/public/_build/results?buildId=54953&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by neobenedict** [comment]
I think you could try it, but I don't know for sure. I use a compiled version of Xamarin (https://github.com/xamarin/xamarin-android/blob/main/Documentation/building/unix/instructions.md).

**Comment by lucas-04** [comment]
![image](https://user-images.githubusercontent.com/95548091/189544679-cb5df576-9716-4850-8dfa-fa87e3b3d05a.png)

I tried but I got stuck in this error, it seems that a file called "google-services.json" is missing in the project directory

**Comment by neobenedict** [comment]
You can use the release one: https://gist.github.com/neobenedict/381293b7ca6706799756d7c5d5f74408

**Comment by lucas-04** [comment]
![image](https://user-images.githubusercontent.com/95548091/189546046-ad445589-a6a4-49ea-aa6c-4b79ed755574.png)

Compile successfully

**Comment by lucas-04** [comment]
Thanks for the help, this was kind of complicated because of the android sdk, ndk and msopenjdk-11 configuration but it sure was a lot easier than compiling xamarin
