### ISSUE TITLE
Android 13 support

### ISSUE THREAD

**Issue by megamoviereturns** [rayshift/translatefgo#61]
Hi, recently my phone was updated to android 13, and I managed to downgrade the files and click 'use this folder', however it says that the folder is empty or inaccessible. Is there any workaround for this? Thank you!

**Comment by neobenedict** [comment]
Unfortunately not, you will have to downgrade your phone to Android 12 or below.

**Comment by neobenedict** [comment]
Might have found a workaround. Give me a day or two.

**Comment by GourmetNewell** [comment]
> Might have found a workaround. Give me a day or two.

Hell yeah

**Comment by neobenedict** [comment]
You can try this:
https://cdn.discordapp.com/attachments/733401773523468398/1024780383365124126/io.rayshift.translatefgo-209d-signed.apk

Let me know if it works. It is a beta so there will be some bugs in that app.

**Comment by GourmetNewell** [comment]
Looks like you've outdone yourself again, neo. It works on Android 13. I salute you.

**Comment by neobenedict** [comment]
Great, the app will live on until google "fixes" this version of it too.

I will publish this formally at a later date.

**Comment by GourmetNewell** [comment]
I'll now do what I should have done long ago and disable automatic updates. Thanks again, mate.

**Comment by megamoviereturns** [comment]
> You can try this: https://cdn.discordapp.com/attachments/733401773523468398/1024780383365124126/io.rayshift.translatefgo-209d-signed.apk
> 
> Let me know if it works. It is a beta so there will be some bugs in that app.

Hi neo, it works for me too. Many thanks for the fix!

**Comment by neobenedict** [comment]
Latest version now supports Android 13.
