### ISSUE TITLE
Still showing MTL for LB5, 5.5

### ISSUE THREAD

**Issue by inboxes** [rayshift/translatefgo#63]
Just installed the most recent english translation, and the recollection quests for LB5 going on right now are clearly MTL. Tested on regular LB5.5 main quests and also saw MTL.

Isn't everything up to LB5.5 supposed to use the official NA script?

**Comment by neobenedict** [comment]
The recollection quests differ from the main quest (I think most? if not all? of the dialogue is the same, but they're placed different internally) and I don't currently have the time to fix that.

Up to 5.2 should be English in the main story.

**Comment by inboxes** [comment]
Ok that makes sense. It's just that the README was saying up to 5.5 is using official NA script, hence the confusion.
