### ISSUE TITLE
dialouge box error

### ISSUE THREAD

**Issue by beorune** [rayshift/translatefgo#66]
hello, my dialouge box seems to be having an issue. is this normal?

![Screenshot_20230211-155325_FateGO](https://user-images.githubusercontent.com/125121836/218250083-e43fe99c-77dc-4642-b3fd-c481ff275d8b.jpg)

**Comment by neobenedict** [comment]
Yeah there's nothing we can do about that unfortunately as the JP version of the game doesn't squish the text like the global region does.
