### ISSUE TITLE
Feature Request : Live MTL if possible?

### ISSUE THREAD

**Issue by krakerz** [rayshift/translatefgo#7]
since in the readme.md it said **real time machine translation**
is it possible to do translation online real time, like Bepinex Autotranslator plugin for example??
so we can get rough TL when the new event released :D 

also thanks for the apps, it helps a lot to understand the story (even without the said feature request added) (for the main story atleast) 👍

**Comment by neobenedict** [comment]
When new events are released they're translated instantly, yeah.

**Comment by krakerz** [comment]
but for released story, like LB5 (for example) cant?
since i just tested it to check the LB5, it seems the MTL didn't works
or did i just misunderstand how the MTL works?

i though it will do MTL for anything in dialogue mode?

if i'm doing wrong, please enlighten me

**Comment by neobenedict** [comment]
LB4, LB5 and LB5.5 aren't in the app yet, due to cost constraints (it was too expensive to translate everything at once), so we're rolling them out slowly. LB4 will come after summer and LB5 and LB5.5 will come before LB6.

Any new content since the app's release is translated automatically.

**Comment by krakerz** [comment]
ok thanks for the confirmation, last question and probably wrong to place it in here

is there any possibility to bring this MTL to outside the dialogue screen?
like for example, skill screen / lore screen (bond) / even CE description with MTL in later date?

and again thanks for the app 👍

**Comment by neobenedict** [comment]
Not really possible without modifying the APK sadly, which is outside the scope of this project.

**Comment by krakerz** [comment]
i see, thanks for the clarification, atleast the good thing is the dialogue cached outside the APK so it can be MTL'ed with this project
that's already big step for us who didn't know any japanese

thank you for the explanation 👍
