### ISSUE TITLE
Problems with Samsung S22+ with Android 13

### ISSUE THREAD

**Issue by LucioMartino** [rayshift/translatefgo#74]
I've been trying to install the app since a few days ago without success, the issue being that when I go through the process of configuring the app I run into the "To protect your privacy, choose a different folder" problem.
I saw the workaround found for this problem, but for some reason I'm unable to downgrade my files app. When I reach the step of "Downgrade your files app using adb install -d -r c:\location\files-downgrade.apk", I get this message on Windows PowerShell:

Performing Streamed Install
adb: failed to install C:\Users\my_username\Documents\files-downgrade.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE: System app: com.google.android.documentsui cannot be downgraded to older than its preloaded version on the system image. Update version code 310851020 is older than current 330543000]
PS C:\platform-tools>

How have people with phones similar to mine managed to successfully install? Is there a way to solve this issue?

**Comment by neobenedict** [comment]
Can you take a picture of when you see the "To protect your privacy" error please?

**Comment by LucioMartino** [comment]
> Can you take a picture of when you see the "To protect your privacy" error please?

The texts in the pictures are in spanish because that's my first language.

In the first picture the button enclosed in the red circle is the one I press to go to the screen where I'm supposed to choose the folder.

In the second picture the button enclosed in the red circle says "Use this folder", but when i try to press that button I get a message saying "To protect your privacy, choose another folder.". And the part enclosed in the blue circle says "This folder cannot be used. To protect your privacy, choose another folder."

![Error01](https://github.com/rayshift/translatefgo/assets/148656248/61356f22-4883-41c8-bd25-b734a8ffc929)
![Error02](https://github.com/rayshift/translatefgo/assets/148656248/148163a6-0a45-4a5e-9d7a-1a51acdc3630)

**Comment by neobenedict** [comment]
The good news is this is probably an app bug (it should launch you directly into the FGO folder to bypass this issue) and not Google patching this for the 4th time.

The bad news is unless I can recreate this locally or in a virtual machine, it's very hard for me to fix. But let's try:

Do you have two storage volumes on your phone (e.g. sd card and internal storage)?

**Comment by LucioMartino** [comment]
> The good news is this is probably an app bug (it should launch you directly into the FGO folder to bypass this issue) and not Google patching this for the 4th time.
> 
> The bad news is unless I can recreate this locally or in a virtual machine, it's very hard for me to fix. But let's try:
> 
> Do you have two storage volumes on your phone (e.g. sd card and internal storage)?

My phone only has one storage volume, it doesn't allow an sd card.

I went to do a little research and found something, and if this is the reason why I can't I'm unable to downgrade my files app, then I may have no hope. Apparently on May this year they released a security patch that (according to an article I'm attaching to this message) prevents downgrades. Here's the article:

https://www.androidpolice.com/android-may-2023-security-patch-no-downgrades-infinitely-old-system-app-versions/

What do you think?

**Comment by neobenedict** [comment]
Usually when the file manager is opened it should put you into the FGO data folder directly, it seems that is failing on your device.

I'll see if I can replicate but no promises on it being a quick or easy fix.

**Comment by LucioMartino** [comment]
> Usually when the file manager is opened it should put you into the FGO data folder directly, which bypasses this error, it seems that is failing on your device.
> 
> I'll see if I can replicate but no promises on it being a quick or easy fix.

Well, let's see what happens. And whatever the result ends up being, thank you so much for taking some of your time to look into this.

**Comment by neobenedict** [comment]
> > Usually when the file manager is opened it should put you into the FGO data folder directly, which bypasses this error, it seems that is failing on your device.
> > I'll see if I can replicate but no promises on it being a quick or easy fix.
> 
> Well, let's see what happens. And whatever the result ends up being, thank you so much for taking some of your time to look into this.

Can you erase the updates of the com.google.android.documentsui app?

https://www.wikihow.com/Uninstall-App-Updates-on-Android

**Comment by neobenedict** [comment]
> > Usually when the file manager is opened it should put you into the FGO data folder directly, which bypasses this error, it seems that is failing on your device.
> > I'll see if I can replicate but no promises on it being a quick or easy fix.
> 
> Well, let's see what happens. And whatever the result ends up being, thank you so much for taking some of your time to look into this.

```adb uninstall com.google.android.documentsui``` worked for another user, downgrades the documentsui app to an older version (even though the command suggests otherwise).

**Comment by LucioMartino** [comment]
> > > Usually when the file manager is opened it should put you into the FGO data folder directly, which bypasses this error, it seems that is failing on your device.
> > > I'll see if I can replicate but no promises on it being a quick or easy fix.
> > 
> > 
> > Well, let's see what happens. And whatever the result ends up being, thank you so much for taking some of your time to look into this.
> 
> `adb uninstall com.google.android.documentsui` worked for another user, downgrades the documentsui app to an older version (even though the command suggests otherwise).

Oh my god this method actually worked!

I used the adb uninstall com.google.android.documentsui command successfully and then proceeded to try to install the translator app, and this time it actually put me into the FGO data folder directly.

I was able to choose that folder, and then the process went on without any other problem.

Thank you so much for your help! You have no idea how much this has made my day.
