### ISSUE TITLE
Can't find install

### ISSUE THREAD

**Issue by EquinoxPhoenix** [rayshift/translatefgo#75]
I can't get the translation to recognize my fgo install from either language.

**Comment by neobenedict** [comment]
#76

You can try the downgrade method in the readme https://github.com/rayshift/translatefgo#error-to-protect-your-privacy-choose-another-folder in the meantime

**Comment by neobenedict** [comment]
What phone do you have?

**Comment by EquinoxPhoenix** [comment]
ZFold3 from Samsung
