### ISSUE TITLE
Samsung S20 FE Android Data File

### ISSUE THREAD

**Issue by QGhostie1942** [rayshift/translatefgo#78]
Yeah the App will not work anymore whenever I go to Android it wont let me drop the file, when I check out 
MyFile > Android > Data 

it won't let me even see it and it says you need computer access.

 When i drop the whole Translate Fate/GO file via through the computer still won't work! so guttered it doesn't work any more

**Comment by neobenedict** [comment]
Dupe of #76 

It's being worked on.

**Comment by neobenedict** [comment]
Maybe useful for you: https://github.com/rayshift/translatefgo/issues/81#issuecomment-1951510995
