### ISSUE TITLE
No english translation for story mode

### ISSUE THREAD

**Issue by BrianKKKK** [rayshift/translatefgo#8]
Hi, I installed the new english translation and I realised it's for new events I think. It says English: Machine TL (LB3 events) & Manual TL (Ooku). Im new to this game and other than this option another option is the spanish translation which means theres only two translation I can install. I watched youtube and I saw the person being able to download the english translation of the story but when I download this app version 1.0.2, there seems to be no option of english translation for the story mode. Will it be back to the app again? Thank you.

**Comment by neobenedict** [comment]
English Translation for Fuyuki to LB2 is currently disabled, it'll be back soon, sorry.

**Comment by BrianKKKK** [comment]
When will it be enabled?

**Comment by neobenedict** [comment]
I'm not sure, but a few days minimum.

**Comment by BrianKKKK** [comment]
Ok can
