### ISSUE TITLE
Tengo un problema para traducir el FGO 

### ISSUE THREAD

**Issue by Caos3036** [rayshift/translatefgo#80]
El problema es que el teléfono no me permite acceder a la data con la intención de usar una carpeta, osea que si intento ubicar y usar la carpeta del FGO el teléfono no me permite acceder a la carpeta de data dónde se encuentra la data de las aplicaciones incluyendo a FGO. Puedo entrar a esta carpeta normalmente osea sin intentar entrar desde otra aplicación. Intente mover la carpeta del FGO a otro lado, aunque funciono para la aplicación de traducción el juego se rompió y no cargo quedándose en pantalla en negro. La verdad probablemente lo único que necesito realmente es evitar que el teléfono me niegue la entrada a la carpeta de data con la intención de usar una de las carpetas.

![IMG_20240121_134112](https://github.com/rayshift/translatefgo/assets/157308215/44076a4b-8e89-4190-8e79-d0dc25645b6e)

**Comment by neobenedict** [comment]
#76

It's being worked on.

**Comment by Caos3036** [comment]
Gracias por responder, esperaré a la próxima actualización para poder traducir el FGO no hay prisa puedo leer bien el inglés así que solo quería postear este problema por si no se sabía o más personas tenían el mismo problema, de nuevo Gracias y no se apuren, gracias por lo que hacen y no sé ajetreen mucho.👍
