### ISSUE TITLE
Fate/Grand Order JP Wasn't found in your system in Latest update 

### ISSUE THREAD

**Issue by AlisherK00** [rayshift/translatefgo#85]
I installed fgo jp and then updated it then installed rayshift latest 2.2.1.0 update and it shows that it cannot find fgo jp in my system, also before this I was using an older version of the rayshift app and it was working until ordeal call came and then whenever I tried to Open the app it either said all not responding (it lagged my mobile, I have Android 14) or either it got to update script page then whenever i click on install it stopped responding, I forgot which was the version number of the previous rayshift I was using.  It also didn't respond when I clicked on Android 11+ setup. 
![Screenshot_2024-03-28-19-14-22-422_io rayshift translatefgo](https://github.com/rayshift/translatefgo/assets/88357600/32c845c7-7be7-4004-8f98-a55e7238625e)

**Comment by neobenedict** [comment]
Fixed in 89fc77/ please update to 2.2.2
