### ISSUE TITLE
Can't move/copy/paste any file into the il2cpp folder 

### ISSUE THREAD

**Issue by New1user-arch** [rayshift/translatefgo#89]
I have the samsung a14 (Android 14) and I play free fire on that I download some config and to apply it I have to paste some file into the il2cpp folder but everytime I try to do it with Zarchiver it says file operation is not supported then I tried another app the com.marc.files app it also says file operation is not supported I don't have any trouble moving files in any other folders but the only folder that I can't access is il2cpp

**Comment by neobenedict** [comment]
Nothing to do with this app.
